version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./cache:/app/cache
      - ./models/trained_models:/app/models/trained_models
    env_file:
      - .env

  frontend:
    build:
      context: ./f1w-frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}        
        NEXT_PUBLIC_API_URL: http://backend:5002
    ports:
      - "3000:3000"
    volumes:
      - ./f1w-frontend:/app         
      - /app/node_modules           
    depends_on:
      - backend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
